# -*- coding: utf-8 -*-
"""ml_yaProj_modelModify6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l6xN2rKOjn8iCfE34rnGjhAoszultbGW
"""

# Commented out IPython magic to ensure Python compatibility.
!pip install scikit-learn Pillow torchvision matplotlib pandas tqdm
# %pip install kaggle
from google.colab import files
# from google.colab import drive
# drive.mount('/content/drive')

from google.colab import drive
from google.colab import files
drive.mount('/content/drive')

files.upload()
! mkdir ~/.kaggle
! cp kaggle.json ~/.kaggle/
! chmod 600 ~/.kaggle/kaggle.json
! kaggle datasets list

!kaggle competitions download -c ml-intensive-yandex-academy-autumn-2024

# !cp /content/ml-intensive-yandex-academy-autumn-2024.zip /content/drive/MyDrive/datasets/

!mkdir Dataset
!unzip -q /content/ml-intensive-yandex-academy-autumn-2024.zip -d /content/Dataset
!rm /content/ml-intensive-yandex-academy-autumn-2024.zip

!cp /content/drive/MyDrive/best_model_m6_e23Plus.pth /content/best_model_m6_e23Plus.pth

# !mkdir Dataset
# !cp /content/drive/MyDrive/dataset/ml-intensive-yandex-academy-autumn-2024.zip /content/Dataset/ml-intensive-yandex-academy-autumn-2024.zip
# !unzip -q /content/Dataset/ml-intensive-yandex-academy-autumn-2024.zip -d /content/Dataset
# !rm /content/Dataset/ml-intensive-yandex-academy-autumn-2024.zip

import random
from pathlib import Path
import os

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
import torch.optim as optim
import torchvision
from torchvision import transforms

from PIL import Image
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split
from torch import nn
from torch.utils.data import DataLoader, Dataset, random_split, ConcatDataset
from tqdm.notebook import tqdm

from torch import nn
from torchsummary import summary
import torch.nn.functional as F


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

class HumanPoseDataset(Dataset):
    def __init__(self, csv_file, img_dir, transform=None):
        self.data = pd.read_csv(csv_file)
        self.img_dir = img_dir
        self.transform = transform

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        img_name = os.path.join(self.img_dir, str(self.data.iloc[idx, 0])) + '.jpg'
        image = Image.open(img_name).convert("RGB")
        label = int(self.data.iloc[idx, 1])  # Class label

        if self.transform:
            image = self.transform(image)

        return image, label

class SEBlock(nn.Module):
    def __init__(self, in_channels, reduction=16):
        super(SEBlock, self).__init__()
        self.global_pool = nn.AdaptiveAvgPool2d(1)
        self.fc1 = nn.Linear(in_channels, in_channels // reduction)
        self.fc2 = nn.Linear(in_channels // reduction, in_channels)

    def forward(self, x):
        batch, channels, _, _ = x.size()
        y = self.global_pool(x).view(batch, channels)
        y = F.relu(self.fc1(y))
        y = torch.sigmoid(self.fc2(y)).view(batch, channels, 1, 1)
        return x * y

class SkipConnectionBlock(nn.Module):
    def __init__(self, in_channels, out_channels):
        super(SkipConnectionBlock, self).__init__()
        self.conv1 = nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1)
        self.bn1 = nn.BatchNorm2d(out_channels)
        self.dropout1 = nn.Dropout2d(0.3)  # added dropout

        self.conv2 = nn.Conv2d(out_channels, out_channels, kernel_size=3, padding=1)
        self.bn2 = nn.BatchNorm2d(out_channels)
        self.dropout2 = nn.Dropout2d(0.3)  # added dropout

        self.se = SEBlock(out_channels)  # add SEBlock

        # We use skip_conv only if the number of channels does not match
        self.use_skip_conv = in_channels != out_channels
        if self.use_skip_conv:
            self.skip_conv = nn.Conv2d(in_channels, out_channels, kernel_size=1)

    def forward(self, x):
        identity = self.skip_conv(x) if self.use_skip_conv else x
        out = F.relu(self.bn1(self.conv1(x)))
        out = self.dropout1(out)  # Dropout after first layer
        out = self.bn2(self.conv2(out))
        out = self.dropout2(out)  # Dropout after second layer
        out = self.se(out)  # apply SEBlock
        out += identity
        return F.relu(out)

class MyModel(nn.Module):
    def __init__(self, num_classes: int):
        super().__init__()
        self.features = nn.Sequential(
            SkipConnectionBlock(3, 16),
            nn.MaxPool2d(2, 2),

            SkipConnectionBlock(16, 64),
            nn.MaxPool2d(2, 2),

            SkipConnectionBlock(64, 128),
            nn.MaxPool2d(2, 2),

            SkipConnectionBlock(128, 256),
            nn.MaxPool2d(2, 2),

            SkipConnectionBlock(256, 512),
            nn.MaxPool2d(2, 2),

            SkipConnectionBlock(512, 1024),
            nn.AdaptiveAvgPool2d((1, 1))
        )

        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(1024, 1024),  # increased number of neurons
            nn.BatchNorm1d(1024),  # added BatchNorm
            nn.ReLU(),
            nn.Dropout(0.5),

            nn.Linear(1024, 256),  # increased number of neurons
            nn.BatchNorm1d(256),  # added BatchNorm
            nn.ReLU(),
            nn.Dropout(0.5),

            nn.Linear(256, num_classes)
        )

    def forward(self, x):
        x = self.features(x)
        x = self.classifier(x)
        return x

model = MyModel(num_classes=20).to(device)

summary(model, (3, 256, 256))

BATCH_SIZE = 64

data_dir = "/content/Dataset/human_poses_data"
train_img_dir = os.path.join(data_dir, "img_train")
test_img_dir = os.path.join(data_dir, "img_test")
train_csv = os.path.join(data_dir, "train_answers.csv")
categories_csv = os.path.join(data_dir, "activity_categories.csv")


# Loading categories
categories = pd.read_csv(categories_csv)
class_names = {row['id']: row['category'] for _, row in categories.iterrows()}


transform_orgin = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

transform_modify = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.RandomHorizontalFlip(),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.1),
    transforms.RandomRotation(5),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])


full_dataset_modify = HumanPoseDataset(csv_file=train_csv, img_dir=train_img_dir, transform=transform_modify)
full_dataset_orgin = HumanPoseDataset(csv_file=train_csv, img_dir=train_img_dir, transform=transform_orgin)

# Combining datasets to increase data volume and robustness
combined_dataset = ConcatDataset([full_dataset_orgin, full_dataset_modify])
train_dataset, valid_dataset = random_split(combined_dataset, [0.8, 0.2])

train_dataloader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
valid_dataloader = DataLoader(valid_dataset, batch_size=BATCH_SIZE, shuffle=False)

test_img_names = sorted(os.listdir(test_img_dir))

#print(train_dataloader)

optimizer = optim.Adam(model.parameters(), lr=0.001)
criterion = nn.CrossEntropyLoss()


train_losses = []
val_losses = []

train_f1_scores = []
val_f1_scores = []

best_val_f1 = 0.0
best_model_path = '/content/drive/MyDrive/best_model_m6_e23Plus.pth'

num_epochs = 15

# Loading a model from a file for further training
checkpoint_path = "best_model_m6_e23Plus.pth"
if os.path.exists(checkpoint_path):
    print("Loading model for fine-tuning...")
    model.load_state_dict(torch.load(checkpoint_path))
    print("Model loaded successfully.")

for epoch in range(num_epochs):
    model.train()
    running_loss = 0.0
    train_true = []
    train_pred = []

    for batch in tqdm(train_dataloader):
        inputs, labels = batch
        inputs, labels = inputs.to(device), labels.to(device)

        optimizer.zero_grad()

        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

        preds = torch.argmax(outputs, dim=1)
        train_true.extend(labels.cpu().numpy())
        train_pred.extend(preds.cpu().numpy())

    train_f1 = f1_score(train_true, train_pred, average='macro')
    train_losses.append(running_loss / len(train_dataloader))
    train_f1_scores.append(train_f1)


    model.eval()
    val_running_loss = 0.0
    val_true = []
    val_pred = []

    # validation cycle, when we evaluate the quality of the model's performance on a delayed sample
    with torch.no_grad():
        for batch in tqdm(valid_dataloader):
            inputs, labels = batch
            inputs, labels = inputs.to(device), labels.to(device)

            outputs = model(inputs)
            loss = criterion(outputs, labels)

            val_running_loss += loss.item()

            preds = torch.argmax(outputs, dim=1)
            val_true.extend(labels.cpu().numpy())
            val_pred.extend(preds.cpu().numpy())

    val_f1 = f1_score(val_true, val_pred, average='macro')
    val_losses.append(val_running_loss / len(valid_dataloader))
    val_f1_scores.append(val_f1)

    # If the resulting model is better than the previous one, we save the checkpoint
    if val_f1 > best_val_f1:
        best_val_f1 = val_f1
        torch.save(model.state_dict(), best_model_path)
        print(f'New best model saved with F1: {best_val_f1:.4f}')

    print(f'Epoch [{epoch+1}/{num_epochs}], '
          f'Train Loss: {train_losses[-1]:.4f}, Train F1: {train_f1:.4f}, '
          f'Val Loss: {val_losses[-1]:.4f}, Val F1: {val_f1:.4f}')


plt.figure(figsize=(14, 5))

plt.subplot(1, 2, 1)
plt.plot(train_losses, label='Train Loss')
plt.plot(val_losses, label='Validation Loss')
plt.title('Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(train_f1_scores, label='Train F1')
plt.plot(val_f1_scores, label='Validation F1')
plt.title('F1 Score')
plt.xlabel('Epoch')
plt.ylabel('F1 Score')
plt.legend()

plt.show()

class InferenceDataset(Dataset):
    def __init__(self, img_names, img_dir, transform=None):
        self.img_names = img_names
        self.img_dir = img_dir
        self.transform = transform

    def __len__(self):
        return len(self.img_names)

    def __getitem__(self, idx):
        img_name = os.path.join(self.img_dir, self.img_names[idx])
        id = int(self.img_names[idx][:-4])
        image = Image.open(img_name).convert("RGB")

        if self.transform:
            image = self.transform(image)

        return id, image


infer_dataset = InferenceDataset(test_img_names, test_img_dir, transform=transform_orgin)
infer_dataloader = DataLoader(infer_dataset, batch_size=64, shuffle=False)


model = MyModel(num_classes=20).to(device)
model.load_state_dict(torch.load(best_model_path))
model.eval()

results = []
for ids, images in tqdm(infer_dataloader):
    images = images.to(device)

    with torch.no_grad():
        outputs = model(images)
        preds = torch.argmax(outputs, dim=1).cpu().numpy()

    for id, pred_class in zip(ids, preds):
        results.append({"id": int(id), "target_feature": pred_class})

df_results = pd.DataFrame(results)
print(df_results)
df_results


df_results.to_csv("submission.csv", index=False)
files.download(best_model_path)
files.download('submission.csv')

